### ISSUE TITLE
snap `unset` is doing `set` with an empty value

### ISSUE THREAD

**Issue by MonicaisHer** [canonical/edgex-snap-hooks#42]
For `unset` a non-existing option, snap will `set` the option with an empty value instead of clearing the existing value. Here is the detail:
```
$ snap get edgex-device-mqtt -d
{}

$ sudo snap unset edgex-device-mqtt config.service.port
$ snap get edgex-device-mqtt -d
{
     "config": {
         "service": {}
    }
}
```

**Comment by farshidtz** [comment]
This is an snap control or snapd issue. IMO, the unset should remove the key-value or set the value to null. Setting it to empty object is problematic because the original value may have been an string.

**Comment by MonicaisHer** [comment]
Agree, I think the snapd set the value to nil anyway. Unset should consider whether the key exists or not first.
https://github.com/snapcore/snapd/blob/master/cmd/snap/cmd_unset.go#L67-L69

**Comment by farshidtz** [comment]
> Agree, I think the snapd set the value to nil anyway. Unset should consider whether the key exists or not first. https://github.com/snapcore/snapd/blob/master/cmd/snap/cmd_unset.go#L67-L69

Perhaps it should be deleted instead: `delete(patchValues, confKey)`

**Comment by MonicaisHer** [comment]
```go
	patchValues := make(map[string]interface{})
	for _, confKey := range x.Positional.ConfKeys {
		// patchValues[confKey] = nil
		delete(patchValues, confKey)
	}
```
WIth this, snap unset doesn't do work anymore.

**Comment by farshidtz** [comment]
> WIth this, snap unset doesn't do work anymore.

Maybe some other part of the code is checking if the value is `nil` and setting it to the empty object.

**Comment by farshidtz** [comment]
Need to report on Snapd's issue tracker.

**Comment by MonicaisHer** [comment]
It might be an EdgeX specific issue:
```
$ snap get -d lxd
{}
$ snap unset lxd service-port
$ snap get -d lxd
{}
```
