### ISSUE TITLE
Support MessageQueue overrides for all device services

### ISSUE THREAD

**Issue by tonyespy** [canonical/edgex-snap-hooks#6]
Version: 2.0.3

The MessageQueue [configuration overrides](https://github.com/canonical/edgex-snap-hooks/blob/master/const.go#L125) currently are only supported for core-data and device-virtual. In fact, these should be usable for any device service using edgex-snap-hooks, not just device-virtual.

**Comment by farshidtz** [comment]
The new environment variable injection feature allows overriding all configurations as long as it is supported via environment variables or [common environment variables](https://docs.edgexfoundry.org/2.2/microservices/configuration/CommonEnvironmentVariables/).
