### ISSUE TITLE
Env file created even when no environment variables are written

### ISSUE THREAD

**Issue by farshidtz** [canonical/edgex-snap-hooks#63]
The library creates the env file for environment variables even when no snap options are set that lead to environment variable assignments.

**Comment by MonicaisHer** [comment]
A check of whether `envVars` is empty  or not could be added, before adding env vars to buffer and creating .env file `os.WriteFile`:
https://github.com/canonical/edgex-snap-hooks/blob/5f794f78f1030a335ff6876dc23a1c98f5bc46ee/options/env.go#L79-L89

**Comment by farshidtz** [comment]
The legacy options have the same issue. After installation, the logs shows the empty files being generated when app options is false.
